config/routes.rb
Rails.application.routes.draw do
  resources :terms
  post '/terms/start' => 'terms#start'
  post '/terms/stop' => 'terms#stop'
  get 'session/create'

  get 'session/destroy'

  root 'home#index'
  get 'home/index'

  get '/auth/:provider/callback', :to => 'session#create'
  post '/auth/:provider/callback', :to => 'session#create'
  get '/logout' => 'session#destroy', :as => :logout

end

app/models/term.rb
class Term < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth['provider']
      user.uid = auth['uid']
      user.name = username(auth)
    end
  end

  private
    def self.username(auth)
      if auth.privider == "twitter"
        auth.info.nickname
      else
        auth.info.name
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/base_controller.rb
class BaseController < ApplicationController
  protect_from_forgery

  def login_required
    if session[:user_id]
      @current_user = User.find(session[:user_id])
    else
      redirect_to root_path
    end

  end

  helper_method :current_user

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/home_controller.rb
# class HomeController < ApplicationController
class HomeController < BaseController
  def index
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def create
    auth = request.env['omniauth.auth']
    user = User.find_by_provider_and_uid(auth['provider'], auth['uid']) || User.create_with_omniauth(auth)
    session[:user_id] = user.id
    redirect_to root_path
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/terms_controller.rb
class TermsController < ApplicationController
  before_action :set_term, only: [:show, :edit, :update, :destroy]

  # GET /terms
  # GET /terms.json
  def index
    @terms = Term.all
  end

  # GET /terms/1
  # GET /terms/1.json
  def show
  end

  # GET /terms/new
  def new
    @term = Term.new
  end

  # GET /terms/1/edit
  def edit
  end

  # POST /terms
  # POST /terms.json
  def create
    @term = Term.new(term_params)

    respond_to do |format|
      if @term.save
#        format.html { redirect_to @term, notice: 'Term was successfully created.' }
        format.html { redirect_to terms_url, notice: 'Term was successfully created.' }
        format.json { render :show, status: :created, location: @term }
      else
        format.html { render :new }
        format.json { render json: @term.errors, status: :unprocessable_entity }
      end
    end
  end

  # POST /terms/start
  # POST /terms/start.json
  def start
    @term = Term.new(started_at: DateTime.now)
    respond_to do |format|
      if @term.save
        format.html { redirect_to terms_url, notice: 'Term was successfully created.' }
        format.json { render :show, status: :created, location: @term }
      else
        format.html { render :new }
        format.json { render json: @term.errors, status: :unprocessable_entity }
      end
    end
  end

  # POST /terms/stop
  # POST /terms/stop.json
  def stop
    @term = Term.last
#    @term = Term.new(ended_at: DateTime.now)
    @term.ended_at = DateTime.now
    respond_to do |format|
      if @term.save
        format.html { redirect_to terms_url, notice: 'Term was successfully stopped.' }
        format.json { render :show, status: :created, location: @term }
      else
        format.html { render :new }
        format.json { render json: @term.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /terms/1
  # PATCH/PUT /terms/1.json
  def update
    respond_to do |format|
      if @term.update(term_params)
        format.html { redirect_to @term, notice: 'Term was successfully updated.' }
        format.json { render :show, status: :ok, location: @term }
      else
        format.html { render :edit }
        format.json { render json: @term.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /terms/1
  # DELETE /terms/1.json
  def destroy
    @term.destroy
    respond_to do |format|
      format.html { redirect_to terms_url, notice: 'Term was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_term
      @term = Term.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def term_params
      params.require(:term).permit(:started_at, :ended_at)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/terms_helper.rb
module TermsHelper
end

app/views/home/index.html.slim
h1 Home#index
p Find me in app/views/home/index.html.slim

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Timecard</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<% if current_user %>
  <%= current_user.name %> <%= link_to 'ログアウト', logout_path %>
<% else %>
  <%= link_to 'ログイン', '/auth/twitter' %>
<% end %>

<%= yield %>

</body>
</html>

app/views/session/create.html.slim
h1 Session#create
p Find me in app/views/session/create.html.slim

app/views/session/destroy.html.slim
h1 Session#destroy
p Find me in app/views/session/destroy.html.slim

app/views/terms/_form.html.slim
= form_for @term do |f|
  - if @term.errors.any?
    #error_explanation
      h2 = "#{pluralize(@term.errors.count, "error")} prohibited this term from being saved:"
      ul
        - @term.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :started_at
    = f.datetime_select :started_at
  .field
    = f.label :ended_at
    = f.datetime_select :ended_at
  .actions = f.submit 'Save'

app/views/terms/edit.html.slim
h1 Editing term

== render 'form'

= link_to 'Show', @term
'|
= link_to 'Back', terms_path

app/views/terms/index.html.slim
p#notice = notice

h1 Listing terms

- if @terms.count == 0 || @terms.last.ended_at
  input#start type="button" value="start"
- else
  input#stop type="button" value="stop"

table
  thead
    tr
      th Started at
      th Ended at
      th
      th
      th

  tbody
    - @terms.each do |term|
      tr
        td = term.started_at
        td = term.ended_at
        td = link_to 'Show', term
        td = link_to 'Edit', edit_term_path(term)
        td = link_to 'Destroy', term, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Term', new_term_path

app/views/terms/new.html.slim
h1 New term

== render 'form'

= link_to 'Back', terms_path

app/views/terms/show.html.slim
p#notice = notice

p
  strong Started at:
  = @term.started_at
p
  strong Ended at:
  = @term.ended_at

= link_to 'Edit', edit_term_path(@term)
'|
= link_to 'Back', terms_path